### ISSUE TITLE
Use abstract types

### ISSUE THREAD

**Issue by vitalijzad** [gredercar/Exercises#7]
Instead of writing

`ArrayList<Integer> multiplesOfN1BelowN = (ArrayList<Integer>) calculateMultiplesBelowN(n1, below);`

You should write

`List<Integer> multiplesOfN1BelowN = calculateMultiplesBelowN(n1, below);`

Also, instead of writing:

`ArrayList<File> filesInDir = new ArrayList<File>(Arrays.asList(files.get(i).listFiles()));`

You should write:

`List<File> filesInDir = Arrays.asList(files.get(i).listFiles());`

**Comment by gredercar** [comment]
Problem solved
